version: '3.8'

services:
  db:
    image: postgres:15
    container_name: eshop-db
    environment:
      POSTGRES_DB: eshop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"

  app:
    build: ./store
    container_name: eshop-app
    ports:
      - "8081:8081"
    depends_on:
      - db