spring:
  datasource:
    url: jdbc:postgresql://db:5432/eshop_db
    username: postgres
    password: test1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
server:
  port: 8081